---
- name: create tchatter infra work directory
  file: path={{ tchatter_app_docker_dir }} state=directory

- name: copy tchatter-app Dockerfile
  template: src=Dockerfile.j2 dest={{ tchatter_app_docker_dir }}/Dockerfile
  register: dockerfile_copy

- name: copy tchatter-app archive
  copy: src={{ local_infra_dir }}/{{ tchatter_app_archive_name }} dest={{ tchatter_app_docker_dir }}/{{ tchatter_app_archive_name }}
  register: archive_copy

- name: create docker image for tchatter-app
  command: docker build -t tchatter/tchatter-app {{ tchatter_app_docker_dir }}
  when: archive_copy.changed or dockerfile_copy.changed
  register: image_creation

# first kills in-container process to speedup container removal
# ("state=absent" first attempts to "stop" it, which may take some time)
- name: kill existing tchatter-app docker container
  docker: image=tchatter/tchatter-app name=tchatter-app state=killed
  ignore_errors: yes
  when: image_creation.changed or (force_new_app_container is defined and force_new_app_container == "yes")

- name: remove existing tchatter-app docker container
  docker: image=tchatter/tchatter-app name=tchatter-app state=absent
  when: image_creation.changed or (force_new_app_container is defined and force_new_app_container == "yes")

- set_fact: tchatter_app_port={{ tchatter_app_port_base + 1 }}

- name: create tchatter-app docker container from image
  docker: image=tchatter/tchatter-app name=tchatter-app state=present detach=yes ports={{ tchatter_app_port }}:{{ tchatter_app_default_port }} links=redis-server:redis
  when: image_creation.changed or (force_new_app_container is defined and force_new_app_container == "yes")

- name: start tchatter-app docker container
  # re-specify creation args to ensure they are used if creation did not occur
  # (because for instance the image did not change but the container is absent for whatever reason)
  docker: image=tchatter/tchatter-app name=tchatter-app state=running detach=yes ports={{ tchatter_app_port }}:{{ tchatter_app_default_port }} links=redis-server:redis
